# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNCryptorDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'RNCryptor-objc'
  # Pods for RNCryptorDemo

  target 'RNCryptorDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNCryptorDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
